obj-$(CONFIG_TEST)		+= test.o mock.o common-mocks.o strerror.o \
  string-stream.o test-stream.o test-executor.o try-catch.o
obj-$(CONFIG_TEST_TEST)		+= \
  test-mock.o mock-macro-test.o mock-test.o strerror-test.o \
  string-stream-test.o test-stream-test.o test-test.o
obj-$(CONFIG_TEST_DEATH_TEST)	+= test-death-test.o
obj-$(CONFIG_EXAMPLE_TEST)	+= example-test.o
