#
# Makefile for the sprd staging modem files
#

ifdef CONFIG_SPRD_SIPC_V2
obj-$(CONFIG_SPRD_SIPC)		+= sipc_v2/
else
obj-$(CONFIG_SPRD_SIPC)		+= sipc/
endif
obj-$(CONFIG_SPRD_CPROC)	+= cproc/
obj-$(CONFIG_SPRD_CRYPTO)	+= crypto/
obj-$(CONFIG_SPRD_IQ)		+= iq/
obj-$(CONFIG_SPRD_HW_DEVICE_DVFS_CP)	+= dvfs/
obj-$(CONFIG_SPRD_MCD)  += mcd/
obj-$(CONFIG_SPRD_MODEM_LOADER)	+= modem_loader/
obj-$(CONFIG_SPRD_PCIE_EP_DEVICE)	+= pcie/
