obj-$(CONFIG_SPRD_LOOK_AT) += sprd_lookat.o
obj-y	+= busmonitor/
obj-y	+= dmc_mpu/
obj-y	+= djtag/
obj-y	+= irq/
obj-$(CONFIG_SPRD_DEBUG)    += sprd_debugfs_frame.o
obj-$(CONFIG_SPRD_CPU_USAGE) += cpu_usage/
obj-$(CONFIG_SPRD_LAST_REGS)    += last_regs/
