
obj-$(CONFIG_SPRD_CRYPTO) += sprd_crypto.o
obj-$(CONFIG_SPRD_CRYPTO) += sprd_rsa.o
obj-$(CONFIG_SPRD_CRYPTO) += sprd_rsassa_pss.o
obj-$(CONFIG_SPRD_CRYPTO) += sprd_pss_mgf1.o
obj-$(CONFIG_SPRD_CRYPTO) += sprd_rsassa_pkcs_v1_5.o
obj-$(CONFIG_SPRD_CRYPTO) += sprd_pkcs_padding.o
obj-$(CONFIG_SPRD_CRYPTO) += sprd_sha256_armv8.o
obj-$(CONFIG_SPRD_CRYPTO) += sprd_sha256_core_armv8.o
obj-$(CONFIG_SPRD_CRYPTO_SW) += sprd_sha256_sw.o
obj-$(CONFIG_SPRD_CRYPTO_SW) += sprd_sha_sw.o
obj-$(CONFIG_SPRD_CRYPTO_TEST) += sprd_crypto_test.o
