ccflags-y :=                            \
        -Idrivers/misc/sprdwcn/include \
        -Idrivers/misc/sprdwcn/platform \
        -Idrivers/misc/sprdwcn/platform/rf
obj-$(CONFIG_SC2342_INTEG) +=  wcn_integrate_dev.o \
	wcn_integrate_boot.o wcn_integrate.o
