obj-$(CONFIG_SPRD_SIPC)     += sipc.o smsg.o smem.o sbuf.o sblock.o sipc_debugfs.o

obj-$(CONFIG_SPRD_SIPC_SPIPE)	+= spipe.o

obj-$(CONFIG_SPRD_SIPC_SPOOL)	+= spool.o

obj-$(CONFIG_SPRD_SIPC_SETH)	+= seth.o

obj-$(CONFIG_SPRD_SIPC_ZERO_COPY_SIPX) += sipx.o

obj-$(CONFIG_SPRD_SIPC_SWCNBLK) += swcn_blk.o
