# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_SPRD) += sc9836-openphone.dtb \
			   sp9860g-1h10.dtb	\
			   sl8541e-1h10.dtb	\
			   sp9863a-1h10.dtb	\
			   sp9863a-1c10.dtb	\
			   sp9863a-2h10.dtb	\
			   sp9863a-3c10.dtb	\
			   ud710-haps.dtb	\
			   ud710-3h10.dtb	\
			   ud710-3h10u.dtb	\
			   ud710-5h10.dtb	\
			   ud710-haps-bkd.dtb   \
			   ud710-orca-haps.dtb	\
			   ud710-2h10.dtb	\
			   udx710-1h10.dtb 	\
			   udx710-2h10.dtb 	\
			   udx710-3h10.dtb 	\
			   udx710-haps.dtb 	\
			   ums518-zebu.dtb     \
			   ums312-haps.dtb	\
			   ums312-1h10.dtb	\
                           ums312-2h10.dtb      \
			   ums312-20c10.dtb	\
			   ums312-3h10-4pro.dtb      \
			   ums512-1h10.dtb	\
			   ums512-20c10.dtb	\
			   ums512-1h10-p.dtb	\
			   ums518-haps.dtb	\
			   ums518-haps-bkd.dtb  \
			   ums7520-haps-native.dtb	\
			   sp9832ep-haps.dtb

dtbo-$(CONFIG_ARCH_SPRD) += \
	sp9863a-1h10-overlay.dtbo \
	sp9863a-1c10-overlay.dtbo \
	sp9863a-2h10-overlay.dtbo \
	sp9863a-3c10-overlay.dtbo \
	sl8541e-1h10-overlay.dtbo \
	ums518-zebu-overlay.dtbo \
	ums312-haps-overlay.dtbo \
	ums312-1h10-overlay.dtbo \
        ums312-2h10-overlay.dtbo \
	ums312-20c10-overlay.dtbo \
	ums312-haps-overlay.dtbo \
        ums312-3h10-4pro-overlay.dtbo \
	ud710-haps-overlay.dtbo \
	ud710-3h10-overlay.dtbo \
	ud710-3h10u-overlay.dtbo \
	ud710-5h10-overlay.dtbo \
	ud710-haps-bkd-overlay.dtbo \
	ud710-orca-haps-overlay.dtbo \
	ud710-2h10-overlay.dtbo \
	ums512-1h10-overlay.dtbo \
	ums512-20c10-overlay.dtbo \
	ums518-haps-overlay.dtbo \
	ums518-haps-bkd-overlay.dtbo \
	ums7520-haps-native-overlay.dtbo \
	sp9832ep-haps-overlay.dtbo

always		:= $(dtb-y) $(dtbo-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
