# adaptive touchscreen
obj-$(CONFIG_TOUCHSCREEN_ADAPTIVE) += ats_core.o
obj-$(CONFIG_TOUCHSCREEN_ADAPTIVE) += ats_loader.o
obj-$(CONFIG_TOUCHSCREEN_ADAPTIVE) += ats_event.o
obj-$(CONFIG_TOUCHSCREEN_ADAPTIVE) += ats_i2c.o
# obj-$(CONFIG_TOUCHSCREEN_ADAPTIVE) += ats_spi.o

# controllers
obj-$(CONFIG_TOUCHSCREEN_ADAPTIVE) += vendors/
