// SPDX-License-Identifier: GPL-2.0+ OR MIT
/*
 * Spreadtrum QOGIRN6PRO platform system global register file
 *
 * Copyright C 2019, Spreadtrum Communications Inc.
 */

#ifndef __DT_BINDINGS_SPRD_QOGIRN6PRO_REGS_H
#define __DT_BINDINGS_SPRD_QOGIRN6PRO_REGS_H

#define REG_PMU_APB_AON_MEM_CTRL                            0x0000
#define REG_PMU_APB_APCPU_TOP_RAM_POWER_CTRL                0x0004
#define REG_PMU_APB_MEM_AUTO_SD_CFG                         0x0008
#define REG_PMU_APB_MEM_AUTO_SLP_CFG                        0x000C
#define REG_PMU_APB_MEM_SD_CFG                              0x0010
#define REG_PMU_APB_MEM_SLP_CFG                             0x0014
#define REG_PMU_APB_RAM_FORCE_ON_CFG                        0x0018
#define REG_PMU_APB_RAM_FORCE_PD_CFG0                       0x001C
#define REG_PMU_APB_RAM_FORCE_PD_CFG1                       0x0020
#define REG_PMU_APB_RAM_FORCE_SLP_CFG                       0x0024
#define REG_PMU_APB_RAM_PD_EN_CTRL                          0x0028
#define REG_PMU_APB_RAM_SLP_EN_CTRL                         0x002C
#define REG_PMU_APB_SRAM_DLY_CTRL_CFG                       0x0030
#define REG_PMU_APB_ANALOG_PHY_PWRDOWN_CFG                  0x00C8
#define REG_PMU_APB_ANALOG_PHY_PWRON_CFG                    0x00CC
#define REG_PMU_APB_MPHY_SLP_CFG                            0x00D0
#define REG_PMU_APB_CSI_4LANE0_SLP_CFG                      0x00D4
#define REG_PMU_APB_CSI_4LANE1_SLP_CFG                      0x00D8
#define REG_PMU_APB_CSI_2P2LANE_SLP_CFG                     0x00DC
#define REG_PMU_APB_DSI0_SLP_CFG                            0x00E0
#define REG_PMU_APB_DSI1_SLP_CFG                            0x00E4
#define REG_PMU_APB_PCIE2_SLP_CFG                           0x00E8
#define REG_PMU_APB_PCIE3_SLP_CFG                           0x00EC
#define REG_PMU_APB_USB3_SLP_CFG                            0x00F0
#define REG_PMU_APB_APCPU_CORE_FORCE_STOP                   0x00F4
#define REG_PMU_APB_APCPU_CORE_WAKEUP_EN                    0x00F8
#define REG_PMU_APB_APCPU_CSYSPWRUP_WAKEUP_EN_CFG           0x00FC
#define REG_PMU_APB_APCPU_SOFT_INT_GEN                      0x0100
#define REG_PMU_APB_BISR_BUSY_STATUS_0                      0x0104
#define REG_PMU_APB_BISR_BUSY_STATUS_1                      0x0108
#define REG_PMU_APB_BISR_BYP_CFG_0                          0x010C
#define REG_PMU_APB_BISR_BYP_CFG_1                          0x0110
#define REG_PMU_APB_BISR_DONE_STATUS_0                      0x0114
#define REG_PMU_APB_BISR_DONE_STATUS_1                      0x0118
#define REG_PMU_APB_BISR_EN_CFG_0                           0x011C
#define REG_PMU_APB_BISR_EN_CFG_1                           0x0120
#define REG_PMU_APB_BISR_FORCE_SEL_0                        0x0124
#define REG_PMU_APB_BISR_FORCE_SEL_1                        0x0128
#define REG_PMU_APB_APCPU_CORE0_INT_DISABLE                 0x012C
#define REG_PMU_APB_APCPU_CORE1_INT_DISABLE                 0x0130
#define REG_PMU_APB_APCPU_CORE2_INT_DISABLE                 0x0134
#define REG_PMU_APB_APCPU_CORE3_INT_DISABLE                 0x0138
#define REG_PMU_APB_APCPU_CORE4_INT_DISABLE                 0x013C
#define REG_PMU_APB_APCPU_CORE5_INT_DISABLE                 0x0140
#define REG_PMU_APB_APCPU_CORE6_INT_DISABLE                 0x0144
#define REG_PMU_APB_APCPU_CORE7_INT_DISABLE                 0x0148
#define REG_PMU_APB_CR8_PHY_TOP_CORE_INT_DISABLE            0x014C
#define REG_PMU_APB_AUD_CEVA_CORE_INT_DISABLE               0x0150
#define REG_PMU_APB_DCDC_CPU0_PWR_DLY_CFG                   0x0154
#define REG_PMU_APB_DCDC_CPU2_PWR_DLY_CFG                   0x0158
#define REG_PMU_APB_DCDC_CPU1_PWR_DLY_CFG                   0x015C
#define REG_PMU_APB_APCPU_TOP_DSLP_ENA                      0x0160
#define REG_PMU_APB_APCPU_CORE0_DSLP_ENA                    0x0164
#define REG_PMU_APB_APCPU_CORE1_DSLP_ENA                    0x0168
#define REG_PMU_APB_APCPU_CORE2_DSLP_ENA                    0x016C
#define REG_PMU_APB_APCPU_CORE3_DSLP_ENA                    0x0170
#define REG_PMU_APB_APCPU_CORE4_DSLP_ENA                    0x0174
#define REG_PMU_APB_APCPU_CORE5_DSLP_ENA                    0x0178
#define REG_PMU_APB_APCPU_CORE6_DSLP_ENA                    0x017C
#define REG_PMU_APB_APCPU_CORE7_DSLP_ENA                    0x0180
#define REG_PMU_APB_CR8_PHY_TOP_DSLP_ENA                    0x0184
#define REG_PMU_APB_AUD_CEVA_DSLP_ENA                       0x0188
#define REG_PMU_APB_DVFS_BLOCK_SHUTDOWN_CFG                 0x018C
#define REG_PMU_APB_GIC_CFG                                 0x0190
#define REG_PMU_APB_MIXED_CFG                               0x0194
#define REG_PMU_APB_PD_AP_CFG                               0x0198
#define REG_PMU_APB_PD_APCPU_TOP_CFG                        0x019C
#define REG_PMU_APB_PD_APCPU_CORE0_CFG                      0x01A0
#define REG_PMU_APB_PD_APCPU_CORE1_CFG                      0x01A4
#define REG_PMU_APB_PD_APCPU_CORE2_CFG                      0x01A8
#define REG_PMU_APB_PD_APCPU_CORE3_CFG                      0x01AC
#define REG_PMU_APB_PD_APCPU_CORE4_CFG                      0x01B0
#define REG_PMU_APB_PD_APCPU_CORE5_CFG                      0x01B4
#define REG_PMU_APB_PD_APCPU_CORE6_CFG                      0x01B8
#define REG_PMU_APB_PD_APCPU_CORE7_CFG                      0x01BC
#define REG_PMU_APB_PD_AI_CFG                               0x01C0
#define REG_PMU_APB_PD_CAMERA_CFG                           0x01C4
#define REG_PMU_APB_PD_VDSP_BLK_CFG                         0x01C8
#define REG_PMU_APB_PD_ISP_BLK_CFG                          0x01CC
#define REG_PMU_APB_PD_DCAM_BLK_CFG                         0x01D0
#define REG_PMU_APB_PD_DPU_VSP_CFG                          0x01D4
#define REG_PMU_APB_PD_VENC0_CFG                            0x01D8
#define REG_PMU_APB_PD_VENC1_CFG                            0x01DC
#define REG_PMU_APB_PD_VDEC_CFG                             0x01E0
#define REG_PMU_APB_PD_GPU_CFG                              0x01E4
#define REG_PMU_APB_PD_GPU_CORE0_CFG                        0x01E8
#define REG_PMU_APB_PD_GPU_CORE1_CFG                        0x01EC
#define REG_PMU_APB_PD_GPU_CORE2_CFG                        0x01F0
#define REG_PMU_APB_PD_GPU_CORE3_CFG                        0x01F4
#define REG_PMU_APB_PD_PHY_CP_CFG                           0x01F8
#define REG_PMU_APB_PD_CR8_PHY_TOP_CFG                      0x01FC
#define REG_PMU_APB_PD_TD_CFG                               0x0200
#define REG_PMU_APB_PD_NR_DL_TOP_CFG                        0x0204
#define REG_PMU_APB_PD_NR_PDS_CFG                           0x0208
#define REG_PMU_APB_PD_NR_SPP_CFG                           0x020C
#define REG_PMU_APB_PD_NR_CST_CFG                           0x0210
#define REG_PMU_APB_PD_UNI_TOP_CFG                          0x0214
#define REG_PMU_APB_PD_LW_PROC_CFG                          0x0218
#define REG_PMU_APB_PD_LCE_CFG                              0x021C
#define REG_PMU_APB_PD_DPFEC_CFG                            0x0220
#define REG_PMU_APB_PD_WCE_CFG                              0x0224
#define REG_PMU_APB_PD_CDMA_PROC0_CFG                       0x0228
#define REG_PMU_APB_PD_CDMA_PROC1_CFG                       0x022C
#define REG_PMU_APB_PD_PS_CP_CFG                            0x0230
#define REG_PMU_APB_PD_AUDIO_CFG                            0x0234
#define REG_PMU_APB_PD_AUD_CEVA_CFG                         0x0238
#define REG_PMU_APB_PD_IPA_CFG                              0x023C
#define REG_PMU_APB_PD_DPU_DP_CFG                           0x0240
#define REG_PMU_APB_PD_PCIE_CFG                             0x0244
#define REG_PMU_APB_PD_PUB_CFG                              0x0248
#define REG_PMU_APB_PD_ISE_CFG                              0x024C
#define REG_PMU_APB_PD_DCDC_CPU1_DCDC_CFG                   0x0260
#define REG_PMU_APB_PWR_DGB_PARAMETER                       0x0264
#define REG_PMU_APB_PWR_STATUS_DBG_0                        0x0268
#define REG_PMU_APB_PWR_STATUS_DBG_1                        0x026C
#define REG_PMU_APB_PWR_STATUS_DBG_2                        0x0270
#define REG_PMU_APB_PWR_STATUS_DBG_3                        0x0274
#define REG_PMU_APB_PWR_STATUS_DBG_4                        0x0278
#define REG_PMU_APB_PWR_STATUS_DBG_5                        0x027C
#define REG_PMU_APB_PWR_STATUS_DBG_6                        0x0280
#define REG_PMU_APB_PWR_STATUS_DBG_7                        0x0284
#define REG_PMU_APB_PWR_STATUS_DBG_8                        0x0288
#define REG_PMU_APB_PWR_STATUS_DBG_9                        0x028C
#define REG_PMU_APB_PWR_STATUS_DBG_10                       0x0290
#define REG_PMU_APB_PWR_STATUS_DBG_11                       0x0294
#define REG_PMU_APB_APCPU_C0_SIMD_RET_MODE                  0x04B0
#define REG_PMU_APB_APCPU_C1_SIMD_RET_MODE                  0x04B4
#define REG_PMU_APB_APCPU_C2_SIMD_RET_MODE                  0x04B8
#define REG_PMU_APB_APCPU_C3_SIMD_RET_MODE                  0x04BC
#define REG_PMU_APB_APCPU_C4_SIMD_RET_MODE                  0x04C0
#define REG_PMU_APB_APCPU_C5_SIMD_RET_MODE                  0x04C4
#define REG_PMU_APB_APCPU_C6_SIMD_RET_MODE                  0x04C8
#define REG_PMU_APB_APCPU_C7_SIMD_RET_MODE                  0x04CC
#define REG_PMU_APB_APCPU_CLUSTER_SW_PACTIVE                0x04D0
#define REG_PMU_APB_APCPU_CLUSTER_SW_PCHANNEL_HANDSHAKE     0x04D4
#define REG_PMU_APB_APCPU_CORE0_SW_PACTIVE                  0x04D8
#define REG_PMU_APB_APCPU_CORE0_SW_PCHANNEL_HANDSHAKE       0x04DC
#define REG_PMU_APB_APCPU_CORE1_SW_PACTIVE                  0x04E0
#define REG_PMU_APB_APCPU_CORE1_SW_PCHANNEL_HANDSHAKE       0x04E4
#define REG_PMU_APB_APCPU_CORE2_SW_PACTIVE                  0x04E8
#define REG_PMU_APB_APCPU_CORE2_SW_PCHANNEL_HANDSHAKE       0x04EC
#define REG_PMU_APB_APCPU_CORE3_SW_PACTIVE                  0x04F0
#define REG_PMU_APB_APCPU_CORE3_SW_PCHANNEL_HANDSHAKE       0x04F4
#define REG_PMU_APB_APCPU_CORE4_SW_PACTIVE                  0x04F8
#define REG_PMU_APB_APCPU_CORE4_SW_PCHANNEL_HANDSHAKE       0x04FC
#define REG_PMU_APB_APCPU_CORE5_SW_PACTIVE                  0x0500
#define REG_PMU_APB_APCPU_CORE5_SW_PCHANNEL_HANDSHAKE       0x0504
#define REG_PMU_APB_APCPU_CORE6_SW_PACTIVE                  0x0508
#define REG_PMU_APB_APCPU_CORE6_SW_PCHANNEL_HANDSHAKE       0x050C
#define REG_PMU_APB_APCPU_CORE7_SW_PACTIVE                  0x0510
#define REG_PMU_APB_APCPU_CORE7_SW_PCHANNEL_HANDSHAKE       0x0514
#define REG_PMU_APB_APCPU_CORINTH_SCU_CLK_GATE_CFG          0x0518
#define REG_PMU_APB_APCPU_DENY_TIME_THRESHOLD_CFG           0x051C
#define REG_PMU_APB_APCPU_MODE_STATE0                       0x0520
#define REG_PMU_APB_APCPU_MODE_STATE1                       0x0524
#define REG_PMU_APB_APCPU_MODE_STATE2                       0x0528
#define REG_PMU_APB_APCPU_MODE_ST_CFG                       0x052C
#define REG_PMU_APB_APCPU_MODE_ST_CFG1                      0x0530
#define REG_PMU_APB_APCPU_MODE_ST_CFG2                      0x0534
#define REG_PMU_APB_APCPU_MODE_ST_CFG3                      0x0538
#define REG_PMU_APB_APCPU_MODE_ST_CGM_EN_CFG                0x053C
#define REG_PMU_APB_APCPU_MODE_ST_FRC_ON_CFG                0x0540
#define REG_PMU_APB_APCPU_PCHANNEL_STATE0                   0x0544
#define REG_PMU_APB_APCPU_PCHANNEL_STATE1                   0x0548
#define REG_PMU_APB_APCPU_SOFT_RST_TYPE_CFG                 0x054C
#define REG_PMU_APB_APCPU_WFI_MARK                          0x0550
#define REG_PMU_APB_DEBUG_RECOV_TYPE_CFG                    0x0554
#define REG_PMU_APB_DEBUG_STATE_MARK                        0x0558
#define REG_PMU_APB_INT_REQ_APCPU_MODE_ST_CLR               0x055C
#define REG_PMU_APB_INT_REQ_APCPU_MODE_ST_ENABLE            0x0560
#define REG_PMU_APB_INT_REQ_APCPU_MODE_ST_RECORD            0x0564
#define REG_PMU_APB_INT_REQ_MODE_ST_APCPU_CLUSTER_INF       0x0568
#define REG_PMU_APB_INT_REQ_MODE_ST_APCPU_CORE0_INF         0x056C
#define REG_PMU_APB_INT_REQ_MODE_ST_APCPU_CORE1_INF         0x0570
#define REG_PMU_APB_INT_REQ_MODE_ST_APCPU_CORE2_INF         0x0574
#define REG_PMU_APB_INT_REQ_MODE_ST_APCPU_CORE3_INF         0x0578
#define REG_PMU_APB_INT_REQ_MODE_ST_APCPU_CORE4_INF         0x057C
#define REG_PMU_APB_INT_REQ_MODE_ST_APCPU_CORE5_INF         0x0580
#define REG_PMU_APB_INT_REQ_MODE_ST_APCPU_CORE6_INF         0x0584
#define REG_PMU_APB_INT_REQ_MODE_ST_APCPU_CORE7_INF         0x0588
#define REG_PMU_APB_OFF_EMU_CLR_IN_DISABLE_CFG              0x058C
#define REG_PMU_APB_OFF_EMU_TO_OFF_CFG                      0x0590
#define REG_PMU_APB_SOFTWARE_APCPU_PACTIVE_ENABLE           0x0594
#define REG_PMU_APB_SOFTWARE_APCPU_PCHANNEL_HANDSHAKE_ENABLE 0x0598
#define REG_PMU_APB_WDG_TRIG_DBG_RECOV_CFG                  0x059C
#define REG_PMU_APB_AP_DSLP_ENA                             0x0640
#define REG_PMU_APB_AUDIO_DSLP_ENA                          0x0644
#define REG_PMU_APB_CDMA_PROC0_DSLP_ENA                     0x0648
#define REG_PMU_APB_CH_DSLP_ENA                             0x064C
#define REG_PMU_APB_DEEP_SLEEP_MON                          0x0650
#define REG_PMU_APB_FORCE_DEEP_SLEEP_CFG                    0x0654
#define REG_PMU_APB_FORCE_LIGHT_SLEEP_CFG                   0x0658
#define REG_PMU_APB_FORCE_PUB_DEEP_SLEEP_CFG                0x065C
#define REG_PMU_APB_FORCE_SYSTEM_SLEEP_CFG                  0x0660
#define REG_PMU_APB_IPA_DSLP_ENA                            0x0664
#define REG_PMU_APB_ISE_ACCESS_DDR_CFG                      0x0668
#define REG_PMU_APB_ISE_DSLP_ENA                            0x066C
#define REG_PMU_APB_ISE_FAST_WAKEUP_CTRL                    0x0670
#define REG_PMU_APB_LIGHT_SLEEP_ENABLE                      0x0674
#define REG_PMU_APB_LIGHT_SLEEP_MON                         0x0678
#define REG_PMU_APB_LIGHT_SLEEP_WAKEUP_EN                   0x067C
#define REG_PMU_APB_PHY_CP_DSLP_ENA                         0x0680
#define REG_PMU_APB_PS_CP_CORE_INT_DISABLE                  0x0684
#define REG_PMU_APB_PS_CP_DSLP_ENA                          0x0688
#define REG_PMU_APB_PUB_DEEP_SLEEP_ENA                      0x068C
#define REG_PMU_APB_PUB_DEEP_SLEEP_WAKEUP_EN                0x0690
#define REG_PMU_APB_PWR_CNT_WAIT_CFG_0                      0x0694
#define REG_PMU_APB_PWR_CNT_WAIT_CFG_1                      0x0698
#define REG_PMU_APB_PWR_CNT_WAIT_CFG_2                      0x069C
#define REG_PMU_APB_PWR_CNT_WAIT_CFG_3                      0x06A0
#define REG_PMU_APB_PWR_CNT_WAIT_CFG_4                      0x06A4
#define REG_PMU_APB_REG_SYS_DDR_PWR_HS_ACK                  0x06A8
#define REG_PMU_APB_SLEEP_STATUS_0                          0x06AC
#define REG_PMU_APB_SLEEP_STATUS_1                          0x06B0
#define REG_PMU_APB_SLEEP_STATUS_2                          0x06B4
#define REG_PMU_APB_SLEEP_XTLON_CTRL                        0x06B8
#define REG_PMU_APB_SP_DSLP_ENA                             0x06BC
#define REG_PMU_APB_UFS_PWR_GATE_BYP_CFG                    0x06C0
#define REG_PMU_APB_DDR_OP_MODE_CFG                         0x07D0
#define REG_PMU_APB_DDR_PHY_RET_CFG                         0x07D4
#define REG_PMU_APB_DDR_SLEEP_CTRL                          0x07D8
#define REG_PMU_APB_DDR_SLEEP_WAIT_CNT                      0x07DC
#define REG_PMU_APB_DDR_SLP_STATUS                          0x07E0
#define REG_PMU_APB_PUB_ACC_RDY                             0x07E4
#define REG_PMU_APB_PUB_AUTO_LIGHT_SLEEP_ENABLE             0x07E8
#define REG_PMU_APB_PUB_DEEP_SLEEP_POLL_0                   0x07EC
#define REG_PMU_APB_PUB_DEEP_SLEEP_POLL_1                   0x07F0
#define REG_PMU_APB_PUB_DEEP_SLEEP_POLL_2                   0x07F4
#define REG_PMU_APB_PUB_DEEP_SLEEP_SEL                      0x07F8
#define REG_PMU_APB_PUB_DFS_FRQ_SEL                         0x07FC
#define REG_PMU_APB_PUB_SLEEP_BYPASS_CFG                    0x0800
#define REG_PMU_APB_PUB_VOL_DOWN_CFG                        0x0804
#define REG_PMU_APB_SMART_LIGHT_SLEEP_ENABLE                0x0808
#define REG_PMU_APB_PLL_CTRL_STATE_0                        0x0898
#define REG_PMU_APB_PLL_CTRL_STATE_1                        0x089C
#define REG_PMU_APB_PLL_CTRL_STATE_2                        0x08A0
#define REG_PMU_APB_PLL_WAIT_CNT_0                          0x08A4
#define REG_PMU_APB_PLL_WAIT_CNT_1                          0x08A8
#define REG_PMU_APB_PLL_WAIT_CNT_2                          0x08AC
#define REG_PMU_APB_PLL_WAIT_CNT_3                          0x08B0
#define REG_PMU_APB_PLL_WAIT_CNT_4                          0x08B4
#define REG_PMU_APB_RCO_WAIT_CNT                            0x08B8
#define REG_PMU_APB_XTL0_REL_CFG                            0x08BC
#define REG_PMU_APB_XTLBUF0_REL_CFG                         0x08C0
#define REG_PMU_APB_XTLBUF1_REL_CFG                         0x08C4
#define REG_PMU_APB_RCO6M_REL_CFG                           0x08C8
#define REG_PMU_APB_RCO60M_REL_CFG                          0x08CC
#define REG_PMU_APB_RCO100M_REL_CFG                         0x08D0
#define REG_PMU_APB_MPLLLIT_REL_CFG                         0x08D4
#define REG_PMU_APB_MPLLMID_REL_CFG                         0x08D8
#define REG_PMU_APB_MPLLBIG_REL_CFG                         0x08DC
#define REG_PMU_APB_MPLLSCU_REL_CFG                         0x08E0
#define REG_PMU_APB_PHYCPR8PLL_REL_CFG                      0x08E4
#define REG_PMU_APB_PSCPR8PLL_REL_CFG                       0x08E8
#define REG_PMU_APB_CPLL_REL_CFG                            0x08EC
#define REG_PMU_APB_V4NRPLL_REL_CFG                         0x08F0
#define REG_PMU_APB_RPLL_REL_CFG                            0x08F4
#define REG_PMU_APB_TGPLL_REL_CFG                           0x08F8
#define REG_PMU_APB_GPLL_REL_CFG                            0x08FC
#define REG_PMU_APB_AIPLL_REL_CFG                           0x0900
#define REG_PMU_APB_VDSPPLL_REL_CFG                         0x0904
#define REG_PMU_APB_AUDPLL_REL_CFG                          0x0908
#define REG_PMU_APB_DPLL0_REL_CFG                           0x090C
#define REG_PMU_APB_DPLL1_REL_CFG                           0x0910
#define REG_PMU_APB_USBPLL_REL_CFG                          0x0914
#define REG_PMU_APB_PCIEPLL_REL_CFG                         0x0918
#define REG_PMU_APB_MPLLLIT_RST_CTRL_CFG                    0x095C
#define REG_PMU_APB_MPLLMID_RST_CTRL_CFG                    0x0960
#define REG_PMU_APB_MPLLBIG_RST_CTRL_CFG                    0x0964
#define REG_PMU_APB_MPLLSCU_RST_CTRL_CFG                    0x0968
#define REG_PMU_APB_PHYCPR8PLL_RST_CTRL_CFG                 0x096C
#define REG_PMU_APB_PSCPR8PLL_RST_CTRL_CFG                  0x0970
#define REG_PMU_APB_CPLL_RST_CTRL_CFG                       0x0974
#define REG_PMU_APB_V4NRPLL_RST_CTRL_CFG                    0x0978
#define REG_PMU_APB_RPLL_RST_CTRL_CFG                       0x097C
#define REG_PMU_APB_TGPLL_RST_CTRL_CFG                      0x0980
#define REG_PMU_APB_GPLL_RST_CTRL_CFG                       0x0984
#define REG_PMU_APB_AIPLL_RST_CTRL_CFG                      0x0988
#define REG_PMU_APB_VDSPPLL_RST_CTRL_CFG                    0x098C
#define REG_PMU_APB_AUDPLL_RST_CTRL_CFG                     0x0990
#define REG_PMU_APB_DPLL0_RST_CTRL_CFG                      0x0994
#define REG_PMU_APB_DPLL1_RST_CTRL_CFG                      0x0998
#define REG_PMU_APB_USBPLL_RST_CTRL_CFG                     0x099C
#define REG_PMU_APB_PCIEPLL_RST_CTRL_CFG                    0x09A0
#define REG_PMU_APB_XTLBUF_WAIT_CNT                         0x09FC
#define REG_PMU_APB_XTL_WAIT_CNT                            0x0A00
#define REG_PMU_APB_APCPU_MODE_ST_SOFT_RST                  0x0BB8
#define REG_PMU_APB_DM_SOFT_RST_0                           0x0BBC
#define REG_PMU_APB_DM_SOFT_RST_1                           0x0BC0
#define REG_PMU_APB_PD_AI_SHUTDOWN_MARK_STATUS              0x0BC4
#define REG_PMU_APB_PD_APCPU_CORE0_SHUTDOWN_MARK_STATUS     0x0BC8
#define REG_PMU_APB_PD_APCPU_CORE1_SHUTDOWN_MARK_STATUS     0x0BCC
#define REG_PMU_APB_PD_APCPU_CORE2_SHUTDOWN_MARK_STATUS     0x0BD0
#define REG_PMU_APB_PD_APCPU_CORE3_SHUTDOWN_MARK_STATUS     0x0BD4
#define REG_PMU_APB_PD_APCPU_CORE4_SHUTDOWN_MARK_STATUS     0x0BD8
#define REG_PMU_APB_PD_APCPU_CORE5_SHUTDOWN_MARK_STATUS     0x0BDC
#define REG_PMU_APB_PD_APCPU_CORE6_SHUTDOWN_MARK_STATUS     0x0BE0
#define REG_PMU_APB_PD_APCPU_CORE7_SHUTDOWN_MARK_STATUS     0x0BE4
#define REG_PMU_APB_PD_APCPU_TOP_SHUTDOWN_MARK_STATUS       0x0BE8
#define REG_PMU_APB_PD_AP_SHUTDOWN_MARK_STATUS              0x0BEC
#define REG_PMU_APB_PD_AUDIO_SHUTDOWN_MARK_STATUS           0x0BF0
#define REG_PMU_APB_PD_AUD_CEVA_SHUTDOWN_MARK_STATUS        0x0BF4
#define REG_PMU_APB_PD_CAMERA_SHUTDOWN_MARK_STATUS          0x0BF8
#define REG_PMU_APB_PD_CDMA_PROC0_SHUTDOWN_MARK_STATUS      0x0BFC
#define REG_PMU_APB_PD_CR8_PHY_TOP_SHUTDOWN_MARK_STATUS     0x0C00
#define REG_PMU_APB_PD_DCAM_BLK_SHUTDOWN_MARK_STATUS        0x0C04
#define REG_PMU_APB_PD_DPFEC_SHUTDOWN_MARK_STATUS           0x0C08
#define REG_PMU_APB_PD_DPU_DP_SHUTDOWN_MARK_STATUS          0x0C0C
#define REG_PMU_APB_PD_DPU_VSP_SHUTDOWN_MARK_STATUS         0x0C10
#define REG_PMU_APB_PD_GPU_SHUTDOWN_MARK_STATUS             0x0C14
#define REG_PMU_APB_PD_IPA_SHUTDOWN_MARK_STATUS             0x0C18
#define REG_PMU_APB_PD_ISE_SHUTDOWN_MARK_STATUS             0x0C1C
#define REG_PMU_APB_PD_ISP_BLK_SHUTDOWN_MARK_STATUS         0x0C20
#define REG_PMU_APB_PD_LCE_SHUTDOWN_MARK_STATUS             0x0C24
#define REG_PMU_APB_PD_LW_PROC_SHUTDOWN_MARK_STATUS         0x0C28
#define REG_PMU_APB_PD_NR_CST_SHUTDOWN_MARK_STATUS          0x0C2C
#define REG_PMU_APB_PD_NR_DL_TOP_SHUTDOWN_MARK_STATUS       0x0C30
#define REG_PMU_APB_PD_NR_PDS_SHUTDOWN_MARK_STATUS          0x0C34
#define REG_PMU_APB_PD_NR_SPP_SHUTDOWN_MARK_STATUS          0x0C38
#define REG_PMU_APB_PD_PCIE_SHUTDOWN_MARK_STATUS            0x0C3C
#define REG_PMU_APB_PD_PHY_CP_SHUTDOWN_MARK_STATUS          0x0C40
#define REG_PMU_APB_PD_PS_CP_SHUTDOWN_MARK_STATUS           0x0C44
#define REG_PMU_APB_PD_PUB_SHUTDOWN_MARK_STATUS             0x0C48
#define REG_PMU_APB_PD_TD_SHUTDOWN_MARK_STATUS              0x0C4C
#define REG_PMU_APB_PD_UNI_TOP_SHUTDOWN_MARK_STATUS         0x0C50
#define REG_PMU_APB_PD_VDEC_SHUTDOWN_MARK_STATUS            0x0C54
#define REG_PMU_APB_PD_VDSP_BLK_SHUTDOWN_MARK_STATUS        0x0C58
#define REG_PMU_APB_PD_VENC0_SHUTDOWN_MARK_STATUS           0x0C5C
#define REG_PMU_APB_PD_VENC1_SHUTDOWN_MARK_STATUS           0x0C60
#define REG_PMU_APB_PD_WCE_SHUTDOWN_MARK_STATUS             0x0C64
#define REG_PMU_APB_REG_SYS_SRST_FRC_LP_ACK                 0x0C68
#define REG_PMU_APB_SOFT_RST_SEL                            0x0C6C
#define REG_PMU_APB_SYS_SOFT_RST                            0x0C70
#define REG_PMU_APB_SYS_SOFT_RST_BUSY                       0x0C74
#define REG_PMU_APB_ALL_PLL_PD_RCO_BYP                      0x0D48
#define REG_PMU_APB_PAD_OUT_CHIP_SLEEP_CFG                  0x0D4C
#define REG_PMU_APB_PAD_OUT_XTL_EN0_CFG                     0x0D50
#define REG_PMU_APB_PAD_OUT_XTL_EN1_CFG                     0x0D54
#define REG_PMU_APB_PAD_OUT_XTL_EN2_CFG                     0x0D58
#define REG_PMU_APB_PAD_OUT_DCDC_APCPU0_EN_CFG              0x0D5C
#define REG_PMU_APB_PAD_OUT_DCDC_APCPU1_EN_CFG              0x0D60
#define REG_PMU_APB_PAD_OUT_DCDC_APCPU2_EN_CFG              0x0D64
#define REG_PMU_APB_CGM_PMU_SEL                             0x0E10
#define REG_PMU_APB_AP_DEEP_SLEEP_CNT                       0x0E14
#define REG_PMU_APB_PHY_CP_DEEP_SLEEP_CNT                   0x0E18
#define REG_PMU_APB_CDMA_PROC0_DEEP_SLEEP_CNT               0x0E1C
#define REG_PMU_APB_PS_CP_DEEP_SLEEP_CNT                    0x0E20
#define REG_PMU_APB_AUDIO_DEEP_SLEEP_CNT                    0x0E24
#define REG_PMU_APB_IPA_DEEP_SLEEP_CNT                      0x0E28
#define REG_PMU_APB_ISE_DEEP_SLEEP_CNT                      0x0E2C
#define REG_PMU_APB_CH_DEEP_SLEEP_CNT                       0x0E30
#define REG_PMU_APB_SP_DEEP_SLEEP_CNT                       0x0E34
#define REG_PMU_APB_PUB_DEEP_SLEEP_CNT                      0x0E38
#define REG_PMU_APB_DEEP_SLEEP_CNT_CLR                      0x0E64
#define REG_PMU_APB_DOMAIN_PWR_DOWN_INT_CLR                 0x0E68
#define REG_PMU_APB_DOMAIN_PWR_UP_INT_CLR                   0x0E6C
#define REG_PMU_APB_ELC_SEL                                 0x0E70
#define REG_PMU_APB_FUNCTION_CNT_CLR                        0x0E74
#define REG_PMU_APB_AP_LIGHT_SLEEP_CNT                      0x0E78
#define REG_PMU_APB_PHY_CP_LIGHT_SLEEP_CNT                  0x0E7C
#define REG_PMU_APB_PS_CP_LIGHT_SLEEP_CNT                   0x0E80
#define REG_PMU_APB_AUDIO_LIGHT_SLEEP_CNT                   0x0E84
#define REG_PMU_APB_IPA_LIGHT_SLEEP_CNT                     0x0E88
#define REG_PMU_APB_ISE_LIGHT_SLEEP_CNT                     0x0E8C
#define REG_PMU_APB_AON_LIGHT_SLEEP_CNT                     0x0E90
#define REG_PMU_APB_PUB_LIGHT_SLEEP_CNT                     0x0E94
#define REG_PMU_APB_LIGHT_SLEEP_CNT_CLR                     0x0EC8
#define REG_PMU_APB_MPLL_WAIT_CLK_DIV_CFG                   0x0ECC
#define REG_PMU_APB_PAD_OUT_CHIP_SLEEP_DUR_CNT              0x0ED0
#define REG_PMU_APB_PAD_OUT_CHIP_SLEEP_EDG_CNT              0x0ED4
#define REG_PMU_APB_PWR_ST_CLK_DIV_CFG                      0x0ED8
#define REG_PMU_APB_SLP_CTRL_CLK_DIV_CFG                    0x0EDC
#define REG_PMU_APB_AP_SYS_STOP_CNT                         0x0EE0
#define REG_PMU_APB_APCPU_TOP_SYS_STOP_CNT                  0x0EE4
#define REG_PMU_APB_AI_SYS_STOP_CNT                         0x0EE8
#define REG_PMU_APB_CAMERA_SYS_STOP_CNT                     0x0EEC
#define REG_PMU_APB_DPU_VSP_SYS_STOP_CNT                    0x0EF0
#define REG_PMU_APB_GPU_SYS_STOP_CNT                        0x0EF4
#define REG_PMU_APB_PHY_CP_SYS_STOP_CNT                     0x0EF8
#define REG_PMU_APB_CDMA_PROC0_SYS_STOP_CNT                 0x0EFC
#define REG_PMU_APB_PS_CP_SYS_STOP_CNT                      0x0F00
#define REG_PMU_APB_AUDIO_SYS_STOP_CNT                      0x0F04
#define REG_PMU_APB_IPA_SYS_STOP_CNT                        0x0F08
#define REG_PMU_APB_ISE_SYS_STOP_CNT                        0x0F0C
#define REG_PMU_APB_SYS_STOP_CNT_CLR                        0x0F30
#define REG_AON_APB_APB_EB0                                 0x0000
#define REG_AON_APB_APB_EB1                                 0x0004
#define REG_AON_APB_APB_EB2                                 0x0008
#define REG_AON_APB_APB_RST0                                0x000C
#define REG_AON_APB_APB_RST1                                0x0010
#define REG_AON_APB_APB_RST2                                0x0014
#define REG_AON_APB_APB_RTC_EB0                             0x0018
#define REG_AON_APB_PWR_CTRL                                0x0024
#define REG_AON_APB_TS_CFG                                  0x0028
#define REG_AON_APB_BOOT_MODE                               0x002C
#define REG_AON_APB_BB_BG_CTRL                              0x0030
#define REG_AON_APB_CP_ARM_JTAG_CTRL                        0x0034
#define REG_AON_APB_DCXO_LC_REG0                            0x003C
#define REG_AON_APB_DCXO_LC_REG1                            0x0040
#define REG_AON_APB_AUDCP_BOOT_PROT                         0x0078
#define REG_AON_APB_AON_REG_PROT                            0x007C
#define REG_AON_APB_AON_APB_CLK_SEL                         0x0080
#define REG_AON_APB_DAP_DJTAG_SEL                           0x0084
#define REG_AON_APB_USER_RSV_FLAG1                          0x0088
#define REG_AON_APB_CM4_SYS_SOFT_RST                        0x008C
#define REG_AON_APB_MDAR_SYS_HSDL_CFG                       0x00C0
#define REG_AON_APB_AUTO_GATE_CTRL0                         0x00D0
#define REG_AON_APB_AUTO_GATE_CTRL1                         0x00D4
#define REG_AON_APB_AP_AXI_CTRL                             0x00D8
#define REG_AON_APB_AON_CHIP_ID0                            0x00E0
#define REG_AON_APB_AON_CHIP_ID1                            0x00E4
#define REG_AON_APB_AON_PLAT_ID0                            0x00E8
#define REG_AON_APB_AON_PLAT_ID1                            0x00EC
#define REG_AON_APB_AON_IMPL_ID                             0x00F0
#define REG_AON_APB_AON_MFT_ID                              0x00F4
#define REG_AON_APB_AON_VER_ID                              0x00F8
#define REG_AON_APB_AON_CHIP_ID                             0x00FC
#define REG_AON_APB_CCIR_RCVR_CFG                           0x0100
#define REG_AON_APB_PLL_BG_CFG                              0x0108
#define REG_AON_APB_LVDSDIS_SEL                             0x010C
#define REG_AON_APB_AUTO_GATE_CTRL2                         0x0114
#define REG_AON_APB_AUTO_GATE_CTRL3                         0x0118
#define REG_AON_APB_APCPU_CLK_CTRL0                         0x011C
#define REG_AON_APB_CGM_ESE                                 0x0120
#define REG_AON_APB_SP_CFG_BUS                              0x0124
#define REG_AON_APB_APB_RST3                                0x0130
#define REG_AON_APB_RC100M_CFG                              0x0134
#define REG_AON_APB_CGM_REG1                                0x0138
#define REG_AON_APB_CGM_CLK_TOP_REG1                        0x013C
#define REG_AON_APB_AUDCP_DSP_CTRL0                         0x0140
#define REG_AON_APB_AUDCP_DSP_CTRL1                         0x0144
#define REG_AON_APB_AUDCP_CTRL                              0x014C
#define REG_AON_APB_WTLCP_LDSP_CTRL0                        0x0150
#define REG_AON_APB_WTLCP_LDSP_CTRL1                        0x0154
#define REG_AON_APB_WTLCP_TDSP_CTRL0                        0x0158
#define REG_AON_APB_WTLCP_TDSP_CTRL1                        0x015C
#define REG_AON_APB_WTLCP_CTRL                              0x0164
#define REG_AON_APB_WTL_WCDMA_EB                            0x0168
#define REG_AON_APB_PCP_AON_EB                              0x0170
#define REG_AON_APB_PCP_SOFT_RST                            0x0174
#define REG_AON_APB_PUBCP_CTRL                              0x0178
#define REG_AON_APB_VECTOR_VDSP                             0x017C
#define REG_AON_APB_WTLCP_LPC_CTRL                          0x0180
#define REG_AON_APB_PUBCP_LPC_CTRL                          0x0184
#define REG_AON_APB_AON_SOC_USB_CTRL                        0x0190
#define REG_AON_APB_ESE_INT_MASK                            0x0194
#define REG_AON_APB_SOFT_RST_AON_ADD1                       0x01A0
#define REG_AON_APB_VDSP_INT_CTRL                           0x01A4
#define REG_AON_APB_EB_AON_ADD1                             0x01B0
#define REG_AON_APB_SYS_DEBUG_BUS_SEL_CFG4                  0x01BC
#define REG_AON_APB_DBG_DJTAG_CTRL                          0x01C0
#define REG_AON_APB_SYS_DEBUG_BUS_SEL_CFG0                  0x01C4
#define REG_AON_APB_SYS_DEBUG_BUS_SEL_CFG1                  0x01C8
#define REG_AON_APB_SYS_DEBUG_BUS_SEL_CFG2                  0x01CC
#define REG_AON_APB_SYS_DEBUG_BUS_SEL_CFG3                  0x01D0
#define REG_AON_APB_PAD_DBG_BUS_SEL_CFG1                    0x01D4
#define REG_AON_APB_PAD_DBG_BUS_SEL_CFG2                    0x01D8
#define REG_AON_APB_PAD_DBG_BUS_SEL_CFG3                    0x01DC
#define REG_AON_APB_PAD_DBG_BUS_SEL_CFG4                    0x01E0
#define REG_AON_APB_PAD_DBG_BUS_SEL_CFG5                    0x01E4
#define REG_AON_APB_PAD_DBG_BUS_SEL_CFG6                    0x01E8
#define REG_AON_APB_PAD_DBG_BUS_SEL_CFG7                    0x01EC
#define REG_AON_APB_PAD_DBG_BUS_DATA_A                      0x01F0
#define REG_AON_APB_PAD_DBG_BUS_DATA_B                      0x01F4
#define REG_AON_APB_PAD_DBG_BUS_DATA_OUT                    0x01F8
#define REG_AON_APB_MBIST_EFUSE_CTRL                        0x01FC
#define REG_AON_APB_OTG_PHY_TUNE                            0x0200
#define REG_AON_APB_OTG_PHY_TEST                            0x0204
#define REG_AON_APB_OTG_PHY_CTRL                            0x0208
#define REG_AON_APB_OTG_CTRL0                               0x020C
#define REG_AON_APB_OTG_CTRL1                               0x0210
#define REG_AON_APB_USB_CLK_REF_SEL                         0x0214
#define REG_AON_APB_LVDSRF_CTRL                             0x0218
#define REG_AON_APB_THM0_CTRL                               0x021C
#define REG_AON_APB_THM1_CTRL                               0x0220
#define REG_AON_APB_THM2_CTRL                               0x0224
#define REG_AON_APB_THM3_CTRL                               0x0228
#define REG_AON_APB_OVERHEAT_CTRL                           0x022C
#define REG_AON_APB_PUBCP_SIM1_TOP_CTRL                     0x0230
#define REG_AON_APB_PUBCP_SIM2_TOP_CTRL                     0x0234
#define REG_AON_APB_PUBCP_SIM3_TOP_CTRL                     0x0238
#define REG_AON_APB_AP_SIM_TOP_CTRL                         0x023C
#define REG_AON_APB_APCPU_MONITOR_STATUS                    0x0280
#define REG_AON_APB_APCPU_DEBUG_PWR_LP_CTRL                 0x0284
#define REG_AON_APB_APCPU_GIC_COL_LP_CTRL                   0x0288
#define REG_AON_APB_APCPU_CLUSTER_ATB_LPC_CTRL              0x028C
#define REG_AON_APB_APCPU_CLUSTER_APB_LPC_CTRL              0x0290
#define REG_AON_APB_APCPU_CLUSTER_GIC_LPC_CTRL              0x0294
#define REG_AON_APB_APCPU_GIC600_GIC_LPC_CTRL               0x0298
#define REG_AON_APB_APCPU_DBG_BLK_LPC_CTRL                  0x029C
#define REG_AON_APB_APCPU_TOP_MTX_M0_LPC_CTRL               0x0300
#define REG_AON_APB_APCPU_TOP_MTX_LPC_PU_NUM_CTRL           0x0304
#define REG_AON_APB_APCPU_CLUSTER_SCU_LPC_CTRL              0x0320
#define REG_AON_APB_APCPU_DDR_AB_LPC_CTRL                   0x0324
#define REG_AON_APB_APCPU_QOS_CTRL                          0x0328
#define REG_AON_APB_MPLL0_CTRL                              0x032C
#define REG_AON_APB_MPLL1_CTRL                              0x0330
#define REG_AON_APB_MPLL2_CTRL                              0x0334
#define REG_AON_APB_MPLL3_CTRL                              0x0338
#define REG_AON_APB_DPLL_CTRL                               0x0340
#define REG_AON_APB_PUB_CLK_GATING_CTRL                     0x0344
#define REG_AON_APB_DDRPHY_VREP                             0x0348
#define REG_AON_APB_CM42AON_LPC_CTRL                        0x0380
#define REG_AON_APB_AON_MTX_MAIN_LPC_CTRL                   0x0384
#define REG_AON_APB_AON_MTX_M0_LPC_CTRL                     0x0388
#define REG_AON_APB_AON_MTX_M1_LPC_CTRL                     0x038C
#define REG_AON_APB_AON_MTX_M2_LPC_CTRL                     0x0390
#define REG_AON_APB_AON_MTX_M3_LPC_CTRL                     0x0394
#define REG_AON_APB_AON_MTX_M4_LPC_CTRL                     0x0398
#define REG_AON_APB_AON_MTX_M5_LPC_CTRL                     0x039C
#define REG_AON_APB_AON_MTX_M6_LPC_CTRL                     0x03A0
#define REG_AON_APB_AON_MTX_S0_LPC_CTRL                     0x03A4
#define REG_AON_APB_AON_MTX_S1_LPC_CTRL                     0x03A8
#define REG_AON_APB_AON_MTX_S2_LPC_CTRL                     0x03AC
#define REG_AON_APB_AON_MTX_S3_LPC_CTRL                     0x03B0
#define REG_AON_APB_AON_MTX_S4_LPC_CTRL                     0x03B4
#define REG_AON_APB_AON_MTX_S5_LPC_CTRL                     0x03B8
#define REG_AON_APB_AON_MTX_S6_LPC_CTRL                     0x03BC
#define REG_AON_APB_AON_MTX_S7_LPC_CTRL                     0x03C0
#define REG_AON_APB_AON_MTX_S8_LPC_CTRL                     0x03C4
#define REG_AON_APB_AON_MTX_S9_LPC_CTRL                     0x03C8
#define REG_AON_APB_AP2GPU_SLI_LPC_CTRL                     0x03CC
#define REG_AON_APB_AP2MM_SLI_LPC_CTRL                      0x03D0
#define REG_AON_APB_WTLCP2DDR_SLI_LPC_CTRL                  0x03D4
#define REG_AON_APB_APCPU2AP_SLI_LPC_CTRL                   0x03D8
#define REG_AON_APB_AUDCP2DDR_SLI_LPC_CTRL                  0x03DC
#define REG_AON_APB_APCPU2DDR_SLI_LPC_CTRL                  0x03E0
#define REG_AON_APB_AON2DDR_BRG_LPC_CTRL                    0x03E4
#define REG_AON_APB_PUBCP2WTLCP_SLI_LPC_CTRL                0x03E8
#define REG_AON_APB_AON_APB_FREQ_CTRL                       0x0400
#define REG_AON_APB_MIPI_CSI_POWER_CTRL                     0x0408
#define REG_AON_APB_APCPU_MERGE_MTX_M0_LPC_CTRL             0x0410
#define REG_AON_APB_APCPU_MERGE_MTX_M1_LPC_CTRL             0x0414
#define REG_AON_APB_APCPU_MERGE_MTX_S0_LPC_CTRL             0x0418
#define REG_AON_APB_GPU_MERGE_MTX_M0_LPC_CTRL               0x041C
#define REG_AON_APB_GPU_MERGE_MTX_M1_LPC_CTRL               0x0420
#define REG_AON_APB_GPU_MERGE_MTX_S0_LPC_CTRL               0x0424
#define REG_AON_APB_GPU2DDR_SLI_LPC_CTRL                    0x0428
#define REG_AON_APB_MM_DCAM2DDR_SLI_LPC_CTRL                0x042C
#define REG_AON_APB_MM_MTX2DDR_SLI_LPC_CTRL                 0x0430
#define REG_AON_APB_IPA12DDR_SLI_LPC_CTRL                   0x0434
#define REG_AON_APB_IPA22DDR_SLI_LPC_CTRL                   0x0438
#define REG_AON_APB_AI2DDR_SLI_LPC_CTRL                     0x043C
#define REG_AON_APB_ESE2DDR_SLI_LPC_CTRL                    0x0440
#define REG_AON_APB_ESE2DDR_ASYNC_BRG_LPC_CTRL              0x0444
#define REG_AON_APB_AP2IPA_SLI_LPC_CTRL                     0x0448
#define REG_AON_APB_AP2AI_SLI_LPC_CTRL                      0x044C
#define REG_AON_APB_AP2IPA_ASYNC_BRG_LPC_CTRL               0x0450
#define REG_AON_APB_C_CHANNEL_SYNC_SEL_CFG                  0x0480
#define REG_AON_APB_APCPU_INT_ENABLE_CTRL0                  0x0500
#define REG_AON_APB_APCPU_INT_ENABLE_CTRL1                  0x0504
#define REG_AON_APB_APCPU_INT_ENABLE_CTRL2                  0x0508
#define REG_AON_APB_APCPU_INT_ENABLE_CTRL3                  0x050C
#define REG_AON_APB_APCPU_INT_ENABLE_CTRL4                  0x0510
#define REG_AON_APB_APCPU_INT_ENABLE_CTRL5                  0x0514
#define REG_AON_APB_SDIO0_CTRL_REG                          0x0520
#define REG_AON_APB_SDIO1_CTRL_REG                          0x0524
#define REG_AON_APB_SDIO2_CTRL_REG                          0x0528
#define REG_AON_APB_EMMC_CTRL_REG                           0x052C
#define REG_AON_APB_WDG_RST_FLAG                            0x0A24
#define REG_AON_APB_BOND_OPT0                               0x0A3C
#define REG_AON_APB_DEVICE_LIFE_CYCLE                       0x0A40
#define REG_AON_APB_RES_REG0                                0x0A44
#define REG_AON_APB_RES_REG1                                0x0A48
#define REG_AON_APB_AON_MTX_PROT_CFG                        0x0A58
#define REG_AON_APB_PLL_LOCK_OUT_SEL                        0x0A64
#define REG_AON_APB_CPU2DDR_BRIDGE_DEBUG_SIGNAL_R           0x0A70
#define REG_AON_APB_AON2DDR_BRIDGE_DEBUG_SIGNAL_W           0x0A74
#define REG_AON_APB_AON2DDR_BRIDGE_DEBUG_SIGNAL_LIST        0x0A78
#define REG_AON_APB_AUD2DDR_BRIDGE_DEBUG_SIGNAL_R           0x0A7C
#define REG_AON_APB_WTL2DDR_BRIDGE_DEBUG_SIGNAL_R           0x0A80
#define REG_AON_APB_DEBUG_FILTER_0                          0x0A90
#define REG_AON_APB_DEBUG_FILTER_1                          0x0A94
#define REG_AON_APB_DEBUG_FILTER_2                          0x0A98
#define REG_AON_APB_DEBUG_FILTER_3                          0x0A9C
#define REG_AON_APB_DEBUG_FILTER_4                          0x0AA0
#define REG_AON_APB_DEBUG_FILTER_5                          0x0AA4
#define REG_AON_APB_LEAKAGE_MAGIC_WORD                      0x0B00
#define REG_AON_APB_LEAKAGE_SWITCH                          0x0B04
#define REG_AON_APB_FUNC_TEST_BOOT_ADDR                     0x0B10
#define REG_AON_APB_CGM_RESCUE                              0x0B14
#define REG_AON_APB_AON_SDIO                                0x0B2C
#define REG_AON_APB_SP_WAKEUP_MASK_EN0                      0x0B84
#define REG_AON_APB_SP_WAKEUP_MASK_EN1                      0x0B88
#define REG_AON_APB_SP_WAKEUP_MASK_EN2                      0x0B8C
#define REG_AON_APB_DBG_BUS_DATA_WTLCP                      0x0B90
#define REG_AON_APB_DBG_BUS_DATA_PUBCP                      0x0B94
#define REG_AON_APB_DBG_BUS_DATA_AUDCP                      0x0B98
#define REG_AON_APB_SDIO_EMMC_POWER_STATUS                  0x0B9C
#define REG_AON_APB_SCC_DBG_BUS                             0x0C00
#define REG_AON_APB_AON_FUNC_CTRL_0                         0x0C04
#define REG_AON_APB_AON_FUNC_CTRL_1                         0x0C08
#define REG_AP_AHB_AHB_EB                                   0x0000
#define REG_AP_AHB_AHB_RST                                  0x0004
#define REG_AP_AHB_AP_SYS_FORCE_SLEEP_CFG                   0x000C
#define REG_AP_AHB_AP_SYS_AUTO_SLEEP_CFG                    0x0010
#define REG_AP_AHB_HOLDING_PEN                              0x0014
#define REG_AP_AHB_CLOCK_FREQUENCY_DOWN                     0x0018
#define REG_AP_AHB_AHB_EB1                                  0x001C
#define REG_AP_AHB_AP_SYS_CLK_EN_FRC_OFF_0                  0x0020
#define REG_AP_AHB_AP_SYS_CLK_EN_FRC_OFF_1                  0x0024
#define REG_AP_AHB_AP_SYS_CLK_EN_FRC_ON_0                   0x0028
#define REG_AP_AHB_AP_SYS_CLK_EN_FRC_ON_1                   0x002C
#define REG_AP_AHB_UFSHC_CLK_CTRL                           0x0040
#define REG_AP_AHB_AP_ASYNC_BRG_AON                         0x0054
#define REG_AP_AHB_AP_ASYNC_BRG_DDR                         0x0058
#define REG_AP_AHB_AP_ASYNC_BRG_APCPU                       0x005C
#define REG_AP_AHB_M0_LPC                                   0x0060
#define REG_AP_AHB_M1_LPC                                   0x0064
#define REG_AP_AHB_M2_LPC                                   0x0068
#define REG_AP_AHB_M3_LPC                                   0x006C
#define REG_AP_AHB_M4_LPC                                   0x0070
#define REG_AP_AHB_M5_LPC                                   0x0074
#define REG_AP_AHB_M6_LPC                                   0x0078
#define REG_AP_AHB_M7_LPC                                   0x007C
#define REG_AP_AHB_MAIN_LPC                                 0x0088
#define REG_AP_AHB_S0_LPC                                   0x008C
#define REG_AP_AHB_S1_LPC                                   0x0090
#define REG_AP_AHB_S2_LPC                                   0x0094
#define REG_AP_AHB_S3_LPC                                   0x0098
#define REG_AP_AHB_S4_LPC                                   0x009C
#define REG_AP_AHB_S5_LPC                                   0x00A0
#define REG_AP_AHB_S6_LPC                                   0x00A4
#define REG_AP_AHB_S7_LPC                                   0x00A8
#define REG_AP_AHB_AP_URGENCY                               0x0130
#define REG_AP_AHB_AP_QOS0                                  0x0140
#define REG_AP_AHB_AP_QOS1                                  0x0144
#define REG_AP_AHB_ASYNC_BRIDGE_IDLE_OVERFLOW               0x0150
#define REG_AP_AHB_ASYNC_BRIDGE_DEBUG_SIGNAL_W_VDSP         0x0154
#define REG_AP_AHB_ASYNC_BRIDGE_DEBUG_SIGNAL_W_DISP         0x0158
#define REG_AP_AHB_ASYNC_BRIDGE_DEBUG_SIGNAL_W_AP           0x015C
#define REG_AP_AHB_CACHE_EMMC_SDIO                          0x3014
#define REG_AP_AHB_CACHE_UFS                                0x3018
#define REG_AP_AHB_CHIP_ID                                  0x30FC
#define REG_AP_APB_APB_EB                                   0x0000
#define REG_AP_APB_APB_RST                                  0x0004
#define REG_AP_APB_APB_MISC_CTRL                            0x0008
#define REG_AP_APB_EB_SEC                                   0x000C
#define REG_AP_APB_APB_EB1                                  0x0010

#endif

