obj-$(CONFIG_SPRD_COMMON_CLK)	+= clk-sprd.o

clk-sprd-y	+= common.o
clk-sprd-y	+= gate.o
clk-sprd-y	+= mux.o
clk-sprd-y	+= div.o
clk-sprd-y	+= composite.o
clk-sprd-y	+= pll.o

## SoC support
obj-$(CONFIG_SPRD_SC9860_CLK)	+= sc9860-clk.o
obj-$(CONFIG_SPRD_SC9832E_CLK)	+= sc9832e-clk.o
obj-$(CONFIG_SPRD_SC7731E_CLK)	+= sc7731e-clk.o
obj-$(CONFIG_SPRD_SC9863A_CLK)	+= sc9863a-clk.o
obj-$(CONFIG_SPRD_SHARKL5_CLK)	+= sharkl5-clk.o
obj-$(CONFIG_SPRD_SHARKL5PRO_CLK)	+= sharkl5pro-clk.o
obj-$(CONFIG_SPRD_ROC1_CLK)	+= roc1-clk.o
obj-$(CONFIG_SPRD_ORCA_CLK)	+= orca-clk.o
