# SPRD audio assistant modules

obj-$(CONFIG_SPRD_AUDIO_AGDSP_ACCESS)		+= agdsp_access/
obj-$(CONFIG_SPRD_AUDIO_DSP_DUMP)		+= audiodspdump/
obj-$(CONFIG_SPRD_AUDIO_MEMORY_MANAGER)		+= audiomem/
obj-$(CONFIG_SPRD_AUDIO_SIPC)			+= audiosipc/
obj-$(CONFIG_SPRD_AUDIO_MCDT)			        += mcdt/
obj-$(CONFIG_SPRD_AUDIO_SAUDIO)			+= saudio/
obj-$(CONFIG_SPRD_HW_DEVICE_DVFS_AGCP) 		+= audiodvfs/
obj-$(CONFIG_SPRD_AUDIO_CPBOOT)				+= audiocpboot/
