obj-$(CONFIG_DISP_PM_DOMAIN_SHARKL3)	+= disp_pm_domain_sharkl3.o
#mm power
obj-$(CONFIG_SPRD_MM_PW_DOMAIN_R6P0) += mmsys_pw_domain_r6p0.o
obj-$(CONFIG_SPRD_CAM_PW_DOMAIN_R5P0) += camsys_pw_domain_r5p0.o
obj-$(CONFIG_SPRD_CAM_PW_DOMAIN_R5P1) += camsys_pw_domain_r5p1.o
obj-$(CONFIG_SPRD_CAM_PW_DOMAIN_R7P0) += camsys_pw_domain_r7p0.o
obj-$(CONFIG_SPRD_CAM_PW_DOMAIN_R4P0) += camsys_pw_domain_r4p0.o
