SPRD_SND_TREE   := sound/soc/sprd/
SPRD_AUDIO_ASSISTANT_TREE := drivers/misc/sprd_audio/
ccflags-y += -I$(SPRD_AUDIO_ASSISTANT_TREE)/audiomem/ \
		-I$(SPRD_AUDIO_ASSISTANT_TREE)/audiosipc/ \
         -I$(SPRD_SND_TREE)/include
obj-y     += sprd_audcp_boot.o
