obj-$(CONFIG_SPRD_VSP) += sprd_vsp.o
obj-$(CONFIG_SPRD_VSP) += vsp_common.o
obj-$(CONFIG_SPRD_VSP) += vsp_isr_func.o
obj-$(CONFIG_SPRD_VSP) += sprd_vsp_pw_domain.o

subdir-ccflags-y += -Idrivers/devfreq/apsys/
