obj-$(CONFIG_SPRD_SIPA) += sipa_phy_v0/

obj-$(CONFIG_SIPA_TEST) += test/

obj-$(CONFIG_SPRD_SIPA) += sipa_api.o sipa_hal.o sipa_nic.o sipa_skb_recv.o \
			   sipa_skb_send.o sipa_rm_res.o sipa_rm_dep_graph.o \
			   sipa_rm.o sipa_rm_peers_list.o sipa_eth.o \
			   sipa_usb_cons.o

obj-$(CONFIG_DEBUG_FS) += sipa_debugfs.o

