obj-$(CONFIG_SPRD_SIPA_DELEGATE) += sipa_delegate.o sipa_dele_cmn.o
obj-$(CONFIG_SPRD_SIPA_DELE_MINIAP_IN_AP) += sipa_dele_miniap_in_ap.o
obj-$(CONFIG_SPRD_SIPA_DELE_AP_IN_MINIAP) += sipa_dele_ap_in_miniap.o
obj-$(CONFIG_SPRD_SIPA_DELE_CP_IN_MINIAP) += sipa_dele_cp_in_miniap.o
